FORMAT: 1A

# TVFlix
We provide a RESTful API for community managed TV Show database. The shows contains different seasons and each season contain it's number of episodes that are advertised by the channel broadcasting the show. Each show and episodes have their own description that are provided by the community. Each show have a place specific for letting the registered user comment. 

# Group Show
A Show represent a TV Show in the database. You can easily get the informations about the show and the different episode of the show.

## Show [/shows/{label}]
A single show with all its informations
+ Parameters
    + label (string, `game-of-thrones`) ... the label that is assigned to the show (usually the show name in lower-case with the space replaced by - )

+ Model (application/hal+json)

    + Body
    
            {  
               "_links":{  
                  "self":{  
                     "href":"/tvflix/shows/game-of-thrones"
                  },
                  "comments":{  
                     "href":"/tvflix/shows/game-of-thrones/comments"
                  },
                  "seasons":{  
                     "href":"/tvflix/shows/game-of-thrones/seasons"
                  }
               },
               "label":"game-of-thrones",
               "title":"Game of Thrones",
               "start_year":"2014",
               "end_year":"None",
               "summary":"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
               "channel":"HBO",
               "tags":[  
                  "drama",
                  "action"
               ]
            }
            
### Get a single show [GET] 
Get the information of the show like it's starting year, which channel, etc ...
+ Response 200

    [Show][]
    



# Group Season

## Season Collection [/shows/{label}/seasons]
Represent a the seasons of a show
+ Parameters
    + label (string, `game-of-thrones`) ... the label that is assigned to the show (usually the show name in lower-case with the space replaced by - )

### List all Seasons [GET]
Get a list of all the season of the wanted show with their nb of episodes.

+ Response 200 (application/hal+json)

        {  
           "_links":{  
              "self":{  
                 "href":"/tvflix/shows/game-of-thrones/seasons"
              }
           },
           "size":"2",
           "_embedded":{  
              "season":[  
                 {  
                    "_links":{  
                       "self":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/1"
                       },
                       "show":{  
                          "href":"/tvflix/shows/game-of-thrones"
                       },
                       "episode":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/1/episodes"
                       }
                    },
                    "number":"1",
                    "episodes":"12",
                    "last_bcast_episode":"12",
                    "start_date":"2013-03-10T12:45:01+00:00"
                 },
                 {  
                    "_links":{  
                       "self":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/2"
                       },
                       "show":{  
                          "href":"/tvflix/shows/game-of-thrones"
                       },
                       "episode":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/2/episodes"
                       }
                    },
                    "number":"2",
                    "episodes":"10",
                    "last_bcast_episode":"10",
                    "start_date":"2014-03-10T12:45:01+00:00"
                 }
              ]
           }
        }
       
## Season [/shows/{label}/seasons/{number}]
Represent a single season of a show. It's a dynamic object generated using the information of the episodes.
 + Parameters
    + label (string, `game-of-thrones`) ... the label that is assigned to the show (usually the show name in lower-case with the space replaced by - )
    + number (number, `1`) ... The number of the season

### Get a single season [GET]
Get the information of the season
 + Response 200 (application/hal+json)
 
        { 
            "_links": { 
                "self": { "href": "/tvflix/shows/game-of-thrones/seasons/1" },
                "show": { "href": "/tvflix/shows/game-of-thrones" },
                "episode": {"href":/tvflix/shows/game-of-thrones/seasons/1/episodes"}
            },
            "number": "1",
            "episodes": "12",
            "last_bcast_episode":"12",
            "start_date":"2013-03-10T12:45:01+00:00"
        }

# Group Episode
## Episodes Collection [/shows/{label}/seasons/{number}/episodes]
Contains all the episodes of a season.
 + Parameters
    + label (string, `game-of-thrones`) ... the label that is assigned to the show (usually the show name in lower-case with the space replaced by - )
    + number (number, `1`) ... The number of the season
    

### Get all Episodes [GET]
Return all the episodes that are registered in the wanted season.
 + Response 200 (application/hal+json)

        {  
           "_links":{  
              "season":{  
                 "href":"/tvflix/shows/game-of-thrones/seasons/1"
              },
              "self":{  
                 "href":"/tvflix/shows/game-of-thrones/seasons/1/episodes"
              }
           },
           "size":"1",
           "_embedded":{  
              "episode":[  
                 {  
                    "_links":{  
                       "self":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/1/episodes/1"
                       },
                       "season":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/1"
                       }
                    },
                    "number":"1",
                    "title":"Dragons",
                    "bcast_date":"2013-03-10T12:45:01+00:00",
                    "summary":"great episode",
                    "season":"1"
                 }
              ]
           }
        }
        
### Add an Episode [POST]
Add an episode to the collection. If the episode already exist the API return a 500 and if the api-key doesn't give you access to this, a 401.
 + Request (application/json)
         {
              "number": "1",
              "title": "Dragons",
              "season": "1",
              "summary": "great episode",
              "bcast_date": "2015-03-10T12:45:01+00:00"
        }

  + Headers
  
            apikey: [client_api_key]


 + Response 201
     [Episode][] 

 + Response 401 (application/json)

        {
            "error":"Invalid api key"
        }

 + Response 500 (application/json)

        {
            "error":"Episode exists already"
        }

## Episode [/shows/{label}/seasons/{number}/episodes/{ep}]
 Episode is an annonced/broadcasted episode of the show.
 + Parameters
    + label (string, `game-of-thrones`) ... the label that is assigned to the show (usually the show name in lower-case with the space replaced by - )
    + number (number, `1`) ... The number of the season
    + ep (number, `1`) ... The number of the episode

 + Model (application/hal+json)

    + Body
    
            {  
                "_links":{  
                   "self":{  
                      "href":"/tvflix/shows/game-of-thrones/seasons/1/episodes/1"
                   },
                   "season":{  
                      "href":"/tvflix/shows/game-of-thrones/seasons/1"
                   }
                },
                "number":"1",
                "title":"Dragons",
                "bcast_date":"2013-03-10T12:45:01+00:00",
                "summary":"great episode",
                "season":"1"
            }

### Get a single Episode [GET]
Get all the information of the wanted episode.
 + Response 200
    [Episode][]

### Update an Episode [PUT]
Update an episode to the collection. If the episode doesn't the API return a 500 and if the api-key doesn't give you access to this, a 401.
 + Request (application/json)
         {
              "number": "1",
              "title": "Dragons",
              "season": "1",
              "summary": "great episode",
              "bcast_date": "2015-03-10T12:45:01+00:00"
        }

   + Headers
  
            apikey: [client_api_key]

 + Response 200
    [Episode][]

 + Response 401 (application/json)

        {
            "error":"Invalid api key"
        }
        
 + Response 500 (application/json)

        {
            "error":"Episode doesn't exists"
        }
        
### Delete an Episode [DELETE]
Delete an episode. If the episode doesn't exist the API return a 500 and if the api-key doesn't give you access to this, a 401.
 + Request (application/json)
     
  + Headers
      
                apikey: [client_api_key] 
 + Response 204

 + Response 401 (application/json)

        {
            "error":"Invalid api key"
        }
        
 + Response 500 (application/json)

        {
            "error":"Episode doesn't exists"
        }

# Group Comment

## Comments Collection [/shows/{label}/comments]
Represent all the comments of a show made by the user.
 + Parameters
    + label (string, `game-of-thrones`) ... the label that is assigned to the show (usually the show name in lower-case with the space replaced by - )
    
### Get all Comments [GET]

Return all the comments of the wanted show.

 + Response 200 (application/hal+json)

        {  
           "_links":{  
              "self":{  
                 "href":"/tvflix/shows/game-of-thrones/comments"
              }
              "show":{  
                 "href":"/tvflix/shows/game-of-thrones"
              }
           },
           "size":"1",
           "_embedded":{  
              "comment":[  
                 {  
                    "_links":{  
                        "self":{  
                             "href":"/tvflix/shows/game-of-thrones/comments"
                      }
                        "show":{  
                             "href":"/tvflix/shows/game-of-thrones"
                      }
                    },
                    "username":"pekka",
                    "comment":"nice tv show, it's best",
                    "posted":"2014-03-10T12:45:01+00:00",
                    "updated": "None"
                 }
              ]
           }
        }

### Add a Comment [POST]
Add a Comment to the collection. If the comment from same user already exists, the API return a 500 and if the api-key doesn't give you access to this, a 401.
 + Request (application/json)
         {
            "comment":"nice tv show, it's best"
        }

  + Headers
  
            apikey: [client_api_key]


 + Response 201
     [Comment][] 

 + Response 401 (application/json)

        {
            "error":"Invalid api key"
        }

 + Response 500 (application/json)

        {
            "error":"Comment to this show already exists"
        }

## Comment [/shows/{label}/comments/{username}]
A user can only make one comment per show.
 + Parameters
    + label (string, `game-of-thrones`) ... the label that is assigned to the show (usually the show name in lower-case with the space replaced by - )
    + username (string, `pekka`) ... The username of the owner of the comment
 + Model (application/hal+json)
 
                 {  
                    "_links":{  
                        "self":{  
                             "href":"/tvflix/shows/game-of-thrones/comments/pekka"
                      }
                        "show":{  
                             "href":"/tvflix/shows/game-of-thrones"
                      }
                    },
                    "username":"pekka",
                    "comment":"nice tv show, it's best",
                    "posted":"2014-03-10T12:45:01+00:00",
                    "updated": "None"
                 }

### Update a Comment [PUT]
Update a comment to the collection. If the comment doesn't exists the API return a 500 and if the api-key doesn't give you access to this, a 401.
 + Request (application/json)
         {
              "comment":"I like it"
        }

   + Headers
  
            apikey: [client_api_key]

 + Response 200
    [Comment][]

 + Response 401 (application/json)

        {
            "error":"Invalid api key"
        }
        
 + Response 500 (application/json)

        {
            "error":"No comment to update"
        }
                
        
### Delete a Comment [DELETE]
Delete a Comment. If the comment doesn't exists the API return a 500 and if the api-key doesn't give you access to this, a 401.
 + Request (application/json)
     
  + Headers
      
                apikey: [client_api_key] 
 + Response 204

 + Response 401 (application/json)

        {
            "error":"Invalid api key"
        }
        
 + Response 500 (application/json)

        {
            "error":"comment doesn't exists"
        }
        
# Group Search 
A Search represent searching either shows or episodes.

## Shows [/search/shows/{keywords}]
Gets all the shows where keyword is associating
+ Parameters
    + keywords (string, `action`) ... the keyword is random string


            
### Search shows [GET]    
Search the database for shows matching the keywords.
+ Response 200

         {  
           "_links":{  
              "self":{  
                 "href":"/tvflix/search/shows/action"
              }
           },
           "size":"1",
           "_embedded":{  
              "show":[  
                 {  
                   "_links":{  
                      "self":{  
                         "href":"/tvflix/shows/game-of-thrones"
                      },
                      "comments":{  
                         "href":"/tvflix/shows/game-of-thrones/comments"
                      },
                      "seasons":{  
                         "href":"/tvflix/shows/game-of-thrones/seasons"
                      }
                   },
                    "label":"game-of-thrones",
                    "title":"Game of Thrones",
                    "start_year":"2014",
                    "end_year":"None",
                    "summary":"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
                    "channel":"HBO",
                    "tags":[  
                      "drama",
                      "action"
                   ]
                 }
              ]
           }
        }

## Episodes [/search/episodes/{keywords}]
Gets all the episodes where keyword is associating
+ Parameters
    + keywords (string, `action`) ... the keyword is random string


            
### Search episodes [GET]  
Search the database for episodes matching the keywords.
+ Response 200

         {  
           "_links":{  
              "self":{  
                 "href":"/tvflix/search/episodes/action"
              }
           },
           "size":"1",
           "_embedded":{  
              "episode":[  
                 {  
                    "_links":{  
                       "self":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/1/episodes/1"
                       },
                       "season":{  
                          "href":"/tvflix/shows/game-of-thrones/seasons/1"
                       }
                    },
                    "number":"1",
                    "title":"Dragons",
                    "bcast_date":"2013-03-10T12:45:01+00:00",
                    "summary":"great episode",
                    "season":"1"
                 }
              ]
           }
        }
    
    